# Generated by Django 5.0.6 on 2024-05-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title) 
            VALUES('test')
        """, """
            DELETE FROM store_collection 
            WHERE title = 'test'
        """)
    ]
